In [24]:
#1.Array Creation
import numpy as np
arr = np.full((2,3),10)
print("Full:",arr, arr.shape, arr.dtype)

empty_array = np.empty((2, 2))

ones_array = np.ones((4, 2))
zeros_like_array = np.zeros_like(ones_array)
ones_like_array = np.ones_like(ones_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

print("\nEmpty array (2x2):\n", empty_array)
print("All ones array (4x2):\n", ones_array)
print("Array of zeros like ones_array:\n", zeros_like_array)
print("\nArray of ones like ones_array:\n", ones_like_array)
print("\nNumPy array from list:\n", numpy_array)

Full: [[10 10 10]
 [10 10 10]] (2, 3) int64

Empty array (2x2):
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array of zeros like ones_array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Array of ones like ones_array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

NumPy array from list:
 [1 2 3 4]


In [58]:
#2.Array Manipulation
import numpy as np

#1
arr = np.arange(10,50)
print("\nvalues ranging from 10 and 49\n",arr)
#2
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\nmatrix:\n",matrix_3x3)
#3
identity_mat = np.eye(3)
print("\nIdentity matrix:\n",identity_mat)
#4
random_arr = np.random.random(30)
mean = random_arr.mean()
print(random_arr)
print("\nmean of random array\n", mean)

#5. 10X10 array with random values
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\nminimum:\n",min_value)
print("maximum:\n",min_value)



values ranging from 10 and 49
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.91894169 0.21051505 0.33800733 0.16737563 0.2542378  0.53004463
 0.0844589  0.96480845 0.86398186 0.61462856 0.99300946 0.54763881
 0.15905425 0.65619772 0.56991448 0.32582612 0.49481997 0.88013146
 0.19562592 0.44684717 0.23121143 0.48958789 0.32831129 0.42549815
 0.01272158 0.28430664 0.30803586 0.59162508 0.48462343 0.38530736]

mean of random array
 0.4585764661798132

minimum:
 0.0009505023266404011
maximum:
 0.0009505023266404011


In [60]:
#6
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with 5th element replaced by 1:\n", zero_array)

#7
arr = [1, 2, 0, 0, 4, 0]
reversed_array = arr[::-1]
print("\nreversed array:\n", reversed_array)

#8 2d with 1 and 0
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n2d array with 1 on border\n", border_arr)

#9
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("Checker board:\n",checkerboard_matrix)


Zero array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

reversed array:
 [0, 4, 0, 0, 2, 1]

2d array with 1 on border
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Checker board:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [63]:
#3.Array Operations
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

sum = x+y
diff = x-y
mult = x*3
sq = np.square(x)

print("Sum of x and y:", sum)
print("Difference between x and y:", diff)
print("Multiplication of x with an integer:", mult)
print("Square of each element of x:\n", sq)

#dot
dot_vw = np.dot(v,w)
dot_xv = np.dot(x,v)
dot_xy = np.dot(x,y)
print("\ndot product between v and w:",dot_vw)
print("dot product between x and v:",dot_xv)
print("dot product between x and y:\n",dot_xy)

#concat
concat_xy = np.concatenate((x,y), axis = 0)
concat_vw = np.vstack((v,w))
print("\nConcatenation and y along row", concat_xy)
print("Concatenation and y along row\n", concat_vw)

try:
  concat_sv = np.concatenate((x,v), axis = 0)
except ValueError as e:
  print(e)

Sum of x and y: [[ 6  8]
 [10 13]]
Difference between x and y: [[-4 -4]
 [-4 -3]]
Multiplication of x with an integer: [[ 3  6]
 [ 9 15]]
Square of each element of x:
 [[ 1  4]
 [ 9 25]]

dot product between v and w: 219
dot product between x and v: [29 77]
dot product between x and y:
 [[19 22]
 [50 58]]

Concatenation and y along row [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation and y along row
 [[ 9 10]
 [11 12]]
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [64]:
#4.1
#Matrix Operations
import numpy as np
#1
A= np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
AxAinv = np.dot(A, A_inv)
identity = np.round(AxAinv)
print("A*A^-1=", identity)

#2
AB = np.dot(A,B)
BA = np.dot(B,A)

are_equal = np.array_equal(AB, BA)
if(are_equal == False):
  print("AB is not equal to B. Proved")

#3
transposeA = np.transpose(A)
transposeB = np.transpose(B)
bTaT = np.dot(transposeB, transposeA)
transpose_AB =  np.transpose(np.dot(A,B))
are_equal = np.array_equal(transpose_AB, bTaT)
if(are_equal == True):
  print("(AB)T = B^T.A^T")


A*A^-1= [[1. 0.]
 [0. 1.]]
AB is not equal to B. Proved
(AB)T = B^T.A^T


In [21]:
#4.1
#Linear equation using Inverse Methods
import numpy as np
A = np.array([[2,-3,1], [1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Coefficient matrix (A):\n", A)
print("\nConstants vector (B):\n", B)
print("\nInverse of A (A_inv):\n", A_inv)
print("\nSolution using A_inv * B (X):", X)

Coefficient matrix (A):
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constants vector (B):
 [-1 -3  9]

Inverse of A (A_inv):
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution using A_inv * B (X): [ 2.  1. -2.]


In [46]:
#4.2
#1.1 Element-wise addition
import time

size = 1000000
list1 = list(range(1, size+ 1))
list2 = list(range(1, size+ 1))

start_time = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
end_time = time.time()

time_taken = end_time - start_time

print(f"Time taken for Element-eise Addition using Python lists: {time_taken} seconds")

Time taken for Element-eise Addition using Python lists: 0.09749841690063477 seconds


In [39]:
#1.2
import numpy as np
import time

size = 1000000
arr1 = np.arange(size)
arr2 = np.arange(size)

#time for numpy arrays
start_time = time.time()
result_array = arr1 + arr2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for Element-wise Addition using NumPy arrays: {numpy_time:.6f} seconds")


Time taken for element-wise addition using NumPy arrays: 0.004986 seconds


In [47]:
#4.2
#2 Element-wise multiplication
import numpy as np
import time

size = 1000000
print("Element-wise multiplication using python list")
list1 = list(range(1, size + 1))
list2 = list(range(1, size + 1))

#measuring for python list
start_time = time.time()
list_multiplication = [x * y for x, y in zip(list1, list2)]
end_time = time.time()

time_list = end_time - start_time
print("Time taken using Python lists:", time_list, "seconds")

#2.2
print("Element-wise multiplication using numpy array")
arr1 = np.arange(1, size + 1)
arr2 = np.arange(1, size + 1)

start_time = time.time()
array_multiplication = arr1 * arr2
end_time = time.time()

time_taken = end_time - start_time

print("Time taken using NumPy arrays:", time_taken, "seconds")

Element-wise multiplication using python list
Time taken using Python lists: 0.09888935089111328 seconds
Element-wise multiplication using numpy array
Time taken using NumPy arrays: 0.005290985107421875 seconds


In [52]:
#4.2
#3 Dot Product
size = 1000000
arr1 = np.arange(size)
arr2 = np.arange(size)

list1 = list(range(1, size + 1))
list2 = list(range(1, size + 1))

#python lists
start_time = time.time()
list_multiplication = [x * y for x, y in zip(list1, list2)]
time_list = time.time() - start_time
print(f"Time taken for Python list dot product: {time_list:.6f} seconds")

#NumPy Arrays
start_time = time.time()
dot_product_array = np.dot(arr1, arr2)
time_numpy_dot = time.time() - start_time
print(f"Time taken for NumPy array dot product: {time_numpy_dot:.6f} seconds")


Time taken for Python list dot product: 0.123353 seconds
Time taken for NumPy array dot product: 0.002342 seconds


In [75]:
#4.2
#4 Matrix Multiplication

import numpy as np
import time

# Using Python Lists
matrix1 = [[i for i in range(1000)] for _ in range(1000)]
matrix2 = [[i for i in range(1000)] for _ in range(1000)]

start_time = time.time()
result_matrix = []
for row in matrix1:
    result_row = []
    for col_idx in range(len(matrix2[0])):
        product_sum = 0
    for i in range(len(row)):
        product_sum += row[i] * matrix2[i][col_idx]
        result_row.append(product_sum)
    result_matrix.append(result_row)
time_list_matrix_mult = time.time() - start_time
print(f"Time taken for Python list matrix multiplication: {time_list_matrix_mult:.5f} seconds")

# Using NumPy Arrays
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result_matrix_np = np.matmul(matrix1_np, matrix2_np)
time_numpy_matrix_mult = time.time() - start_time
print(f"Time taken for NumPy array matrix multiplication: {time_numpy_matrix_mult:.5f} seconds")


Time taken for Python list matrix multiplication: 0.67363 seconds
Time taken for NumPy array matrix multiplication: 5.87985 seconds


In [ ]:
#Examples
#importing numpy and array type
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [ ]:
#shape of an array
#create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3], [4,5,6]])
array_3d = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
#print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
  print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [ ]:
#Reshaping an array
import numpy as np
array = np.array([[1,2,3,4], [4,5,6,7]]) #shape(2,3)
reshaped_array = array.reshape(4,2) #6 elements reshape it to (3,2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 4) 
Reshaped Shape: (4, 2)


In [ ]:
#arrays with evenly spaced values -> arange
import numpy as np
a = np.arange(1, 10) #returns numpy array instead of list
print(a)
x = range(1, 10)
print(x)
print(list(x))

x = np.arange(10.4)
print(x)

x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
#linspace defines the nummber of steps
print(np.linspace(1,10))
print(np.linspace(1, 10, 7))
print(np.linspace(1, 10, 5, endpoint=False))

#endpooint default true
#linspace ko step default 50 uuntil specified

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.  2.8 4.6 6.4 8.2]


In [ ]:
#initializing an array
import numpy as np
ones_array = np.ones((2,3))
zeros_array = np.zeros((3, 2))

identity_matrix = np.eye(3)  #creates 3x3 array
print(identity_matrix, ones_array, zeros_array, sep='\n\n')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
empty_array

array([[4.86182538e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [ ]:
#converting list to array using np.array
array_list = np.array([1,2,3])
array_tuple = np.array((5,6,7))
array_nestedList = np.array([[1,2,3], [4,5,6]])
print(array_list, array_tuple, array_nestedList, sep='\n')


[1 2 3]
[5 6 7]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Using shape of an existing array
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4.86182545e-310 0.00000000e+000 6.67011755e-310]
 [6.67011740e-310 6.67011740e-310 6.67011740e-310]]


In [ ]:
import numpy as np
arr= np.empty((2,2))
arr

array([[4.86182494e-310, 0.00000000e+000],
       [1.22568369e+213, 1.22776923e+213]])

In [ ]:
all_one = np.ones((4,2))
all_one

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [48]:
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using @ operator
result_at = A @ B
print("Result with @ operator:\n", result_at) # Output shape: (2, 2)
# Matrix multiplication using np.matmul
result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul) # Output shape: (2, 2)

Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]
